# Generated by Django 4.0.4 on 2022-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitprojects', '0002_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='gitprojects.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='gitprojects.category'),
        ),
    ]
